"""`alpha bootstrap` 的长列契约 helper。"""

from __future__ import annotations

from typing import Final


ALPHA_FORMAL_SIGNAL_EVENT_REQUIRED_COLUMNS: Final[dict[str, str]] = {
    "signal_nk": "TEXT",
    "instrument": "TEXT",
    "signal_date": "DATE",
    "asof_date": "DATE",
    "trigger_family": "TEXT",
    "trigger_type": "TEXT",
    "pattern_code": "TEXT",
    "formal_signal_status": "TEXT",
    "trigger_admissible": "BOOLEAN",
    "admission_verdict_code": "TEXT",
    "admission_verdict_owner": "TEXT",
    "admission_reason_code": "TEXT",
    "admission_audit_note": "TEXT",
    "filter_gate_code": "TEXT",
    "filter_reject_reason_code": "TEXT",
    "major_state": "TEXT",
    "trend_direction": "TEXT",
    "reversal_stage": "TEXT",
    "wave_id": "BIGINT",
    "current_hh_count": "BIGINT",
    "current_ll_count": "BIGINT",
    "malf_context_4": "TEXT",
    "lifecycle_rank_high": "BIGINT",
    "lifecycle_rank_total": "BIGINT",
    "daily_source_context_nk": "TEXT",
    "weekly_major_state": "TEXT",
    "weekly_trend_direction": "TEXT",
    "weekly_reversal_stage": "TEXT",
    "weekly_source_context_nk": "TEXT",
    "monthly_major_state": "TEXT",
    "monthly_trend_direction": "TEXT",
    "monthly_reversal_stage": "TEXT",
    "monthly_source_context_nk": "TEXT",
    "source_family_event_nk": "TEXT",
    "family_code": "TEXT",
    "source_family_contract_version": "TEXT",
    "family_role": "TEXT",
    "family_bias": "TEXT",
    "malf_alignment": "TEXT",
    "malf_phase_bucket": "TEXT",
    "family_source_context_fingerprint": "TEXT",
    "wave_life_percentile": "DOUBLE",
    "remaining_life_bars_p50": "DOUBLE",
    "remaining_life_bars_p75": "DOUBLE",
    "termination_risk_bucket": "TEXT",
    "stage_percentile_decision_code": "TEXT",
    "stage_percentile_action_owner": "TEXT",
    "stage_percentile_note": "TEXT",
    "stage_percentile_contract_version": "TEXT",
    "source_trigger_event_nk": "TEXT",
    "signal_contract_version": "TEXT",
    "first_seen_run_id": "TEXT",
    "last_materialized_run_id": "TEXT",
    "created_at": "TIMESTAMP",
    "updated_at": "TIMESTAMP",
}

ALPHA_FORMAL_SIGNAL_RUN_EVENT_REQUIRED_COLUMNS: Final[dict[str, str]] = {
    "run_id": "TEXT",
    "signal_nk": "TEXT",
    "materialization_action": "TEXT",
    "formal_signal_status": "TEXT",
    "admission_verdict_code": "TEXT",
    "admission_verdict_owner": "TEXT",
    "admission_reason_code": "TEXT",
    "source_family_event_nk": "TEXT",
    "family_code": "TEXT",
    "family_role": "TEXT",
    "malf_alignment": "TEXT",
    "family_source_context_fingerprint": "TEXT",
    "stage_percentile_decision_code": "TEXT",
    "stage_percentile_action_owner": "TEXT",
    "source_trigger_event_nk": "TEXT",
    "recorded_at": "TIMESTAMP",
}
