"""`malf bootstrap` 的 required-column 补齐映射。"""

from __future__ import annotations

from typing import Final

from mlq.malf.bootstrap_tables import (
    MALF_CANONICAL_CHECKPOINT_TABLE,
    MALF_CANONICAL_RUN_TABLE,
    MALF_CANONICAL_WORK_QUEUE_TABLE,
    MALF_EXTREME_PROGRESS_LEDGER_TABLE,
    MALF_LEDGER_CONTRACT_TABLE,
    MALF_MECHANISM_CHECKPOINT_TABLE,
    MALF_MECHANISM_RUN_TABLE,
    MALF_PIVOT_LEDGER_TABLE,
    MALF_RUN_CONTEXT_SNAPSHOT_TABLE,
    MALF_RUN_STRUCTURE_SNAPSHOT_TABLE,
    MALF_RUN_TABLE,
    MALF_SAME_LEVEL_STATS_TABLE,
    MALF_STATE_SNAPSHOT_TABLE,
    MALF_WAVE_LEDGER_TABLE,
    MALF_WAVE_LIFE_CHECKPOINT_TABLE,
    MALF_WAVE_LIFE_PROFILE_TABLE,
    MALF_WAVE_LIFE_RUN_TABLE,
    MALF_WAVE_LIFE_SNAPSHOT_TABLE,
    MALF_WAVE_LIFE_WORK_QUEUE_TABLE,
    PAS_CONTEXT_SNAPSHOT_TABLE,
    PIVOT_CONFIRMED_BREAK_LEDGER_TABLE,
    SAME_TIMEFRAME_STATS_PROFILE_TABLE,
    SAME_TIMEFRAME_STATS_SNAPSHOT_TABLE,
    STRUCTURE_CANDIDATE_SNAPSHOT_TABLE,
)


MALF_REQUIRED_COLUMNS: Final[dict[str, dict[str, str]]] = {
    MALF_LEDGER_CONTRACT_TABLE: {
        "contract_key": "TEXT",
        "storage_mode": "TEXT",
        "native_timeframe": "TEXT",
        "contract_version": "TEXT",
        "declared_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_RUN_TABLE: {
        "run_id": "TEXT",
        "runner_name": "TEXT",
        "runner_version": "TEXT",
        "run_status": "TEXT",
        "signal_start_date": "DATE",
        "signal_end_date": "DATE",
        "bounded_instrument_count": "BIGINT",
        "source_price_table": "TEXT",
        "adjust_method": "TEXT",
        "malf_contract_version": "TEXT",
        "started_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "summary_json": "TEXT",
    },
    PAS_CONTEXT_SNAPSHOT_TABLE: {
        "context_nk": "TEXT",
        "entity_code": "TEXT",
        "entity_name": "TEXT",
        "signal_date": "DATE",
        "asof_date": "DATE",
        "source_context_nk": "TEXT",
        "malf_context_4": "TEXT",
        "lifecycle_rank_high": "BIGINT",
        "lifecycle_rank_total": "BIGINT",
        "calc_date": "DATE",
        "adjust_method": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    STRUCTURE_CANDIDATE_SNAPSHOT_TABLE: {
        "candidate_nk": "TEXT",
        "instrument": "TEXT",
        "instrument_name": "TEXT",
        "signal_date": "DATE",
        "asof_date": "DATE",
        "new_high_count": "BIGINT",
        "new_low_count": "BIGINT",
        "refresh_density": "DOUBLE",
        "advancement_density": "DOUBLE",
        "is_failed_extreme": "BOOLEAN",
        "failure_type": "TEXT",
        "adjust_method": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_RUN_CONTEXT_SNAPSHOT_TABLE: {
        "run_id": "TEXT",
        "context_nk": "TEXT",
        "materialization_action": "TEXT",
        "recorded_at": "TIMESTAMP",
    },
    MALF_RUN_STRUCTURE_SNAPSHOT_TABLE: {
        "run_id": "TEXT",
        "candidate_nk": "TEXT",
        "materialization_action": "TEXT",
        "recorded_at": "TIMESTAMP",
    },
    MALF_MECHANISM_RUN_TABLE: {
        "run_id": "TEXT",
        "runner_name": "TEXT",
        "runner_version": "TEXT",
        "run_status": "TEXT",
        "signal_start_date": "DATE",
        "signal_end_date": "DATE",
        "bounded_instrument_count": "BIGINT",
        "source_context_table": "TEXT",
        "source_structure_input_table": "TEXT",
        "timeframe": "TEXT",
        "stats_sample_version": "TEXT",
        "mechanism_contract_version": "TEXT",
        "started_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "summary_json": "TEXT",
    },
    MALF_MECHANISM_CHECKPOINT_TABLE: {
        "instrument": "TEXT",
        "timeframe": "TEXT",
        "last_signal_date": "DATE",
        "last_asof_date": "DATE",
        "last_run_id": "TEXT",
        "source_context_nk": "TEXT",
        "updated_at": "TIMESTAMP",
    },
    PIVOT_CONFIRMED_BREAK_LEDGER_TABLE: {
        "break_event_nk": "TEXT",
        "instrument": "TEXT",
        "timeframe": "TEXT",
        "guard_pivot_id": "TEXT",
        "guard_pivot_role": "TEXT",
        "origin_context": "TEXT",
        "trigger_bar_dt": "DATE",
        "trigger_price_proxy": "DOUBLE",
        "break_direction": "TEXT",
        "confirmation_status": "TEXT",
        "confirmation_bar_dt": "DATE",
        "confirmation_pivot_id": "TEXT",
        "confirmation_pivot_role": "TEXT",
        "source_context_nk": "TEXT",
        "source_candidate_nk": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    SAME_TIMEFRAME_STATS_PROFILE_TABLE: {
        "stats_profile_nk": "TEXT",
        "universe": "TEXT",
        "timeframe": "TEXT",
        "regime_family": "TEXT",
        "metric_name": "TEXT",
        "sample_version": "TEXT",
        "sample_size": "BIGINT",
        "p10": "DOUBLE",
        "p25": "DOUBLE",
        "p50": "DOUBLE",
        "p75": "DOUBLE",
        "p90": "DOUBLE",
        "mean": "DOUBLE",
        "std": "DOUBLE",
        "bucket_definition_json": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    SAME_TIMEFRAME_STATS_SNAPSHOT_TABLE: {
        "stats_snapshot_nk": "TEXT",
        "instrument": "TEXT",
        "timeframe": "TEXT",
        "signal_date": "DATE",
        "asof_bar_dt": "DATE",
        "regime_family": "TEXT",
        "sample_version": "TEXT",
        "stats_contract_version": "TEXT",
        "source_context_nk": "TEXT",
        "source_candidate_nk": "TEXT",
        "new_high_count_percentile": "DOUBLE",
        "new_low_count_percentile": "DOUBLE",
        "refresh_density_percentile": "DOUBLE",
        "advancement_density_percentile": "DOUBLE",
        "exhaustion_risk_bucket": "TEXT",
        "reversal_probability_bucket": "TEXT",
        "source_profile_refs_json": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_CANONICAL_RUN_TABLE: {
        "run_id": "TEXT",
        "runner_name": "TEXT",
        "runner_version": "TEXT",
        "run_status": "TEXT",
        "signal_start_date": "DATE",
        "signal_end_date": "DATE",
        "bounded_scope_count": "BIGINT",
        "pivot_confirmation_window": "BIGINT",
        "source_price_table": "TEXT",
        "source_adjust_method": "TEXT",
        "canonical_contract_version": "TEXT",
        "timeframe_list_json": "TEXT",
        "started_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "summary_json": "TEXT",
    },
    MALF_CANONICAL_WORK_QUEUE_TABLE: {
        "queue_nk": "TEXT",
        "scope_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "dirty_reason": "TEXT",
        "source_last_trade_date": "DATE",
        "queue_status": "TEXT",
        "enqueued_at": "TIMESTAMP",
        "claimed_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "first_seen_run_id": "TEXT",
        "last_claimed_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "updated_at": "TIMESTAMP",
    },
    MALF_CANONICAL_CHECKPOINT_TABLE: {
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "last_completed_bar_dt": "DATE",
        "tail_start_bar_dt": "DATE",
        "tail_confirm_until_dt": "DATE",
        "last_wave_id": "BIGINT",
        "last_run_id": "TEXT",
        "updated_at": "TIMESTAMP",
    },
    MALF_PIVOT_LEDGER_TABLE: {
        "pivot_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "pivot_type": "TEXT",
        "pivot_bar_dt": "DATE",
        "confirmed_at": "DATE",
        "pivot_price": "DOUBLE",
        "prior_pivot_nk": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_WAVE_LEDGER_TABLE: {
        "wave_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "wave_id": "BIGINT",
        "direction": "TEXT",
        "major_state": "TEXT",
        "reversal_stage": "TEXT",
        "start_bar_dt": "DATE",
        "end_bar_dt": "DATE",
        "active_flag": "BOOLEAN",
        "start_pivot_nk": "TEXT",
        "end_pivot_nk": "TEXT",
        "hh_count": "BIGINT",
        "ll_count": "BIGINT",
        "bar_count": "BIGINT",
        "wave_high": "DOUBLE",
        "wave_low": "DOUBLE",
        "range_ratio": "DOUBLE",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_EXTREME_PROGRESS_LEDGER_TABLE: {
        "extreme_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "wave_id": "BIGINT",
        "extreme_seq": "BIGINT",
        "extreme_type": "TEXT",
        "break_base_extreme_nk": "TEXT",
        "record_bar_dt": "DATE",
        "record_price": "DOUBLE",
        "cumulative_count": "BIGINT",
        "major_state": "TEXT",
        "trend_direction": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_STATE_SNAPSHOT_TABLE: {
        "snapshot_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "asof_bar_dt": "DATE",
        "major_state": "TEXT",
        "trend_direction": "TEXT",
        "reversal_stage": "TEXT",
        "wave_id": "BIGINT",
        "last_confirmed_h_bar_dt": "DATE",
        "last_confirmed_h_price": "DOUBLE",
        "last_confirmed_l_bar_dt": "DATE",
        "last_confirmed_l_price": "DOUBLE",
        "last_valid_hl_bar_dt": "DATE",
        "last_valid_hl_price": "DOUBLE",
        "last_valid_lh_bar_dt": "DATE",
        "last_valid_lh_price": "DOUBLE",
        "current_hh_count": "BIGINT",
        "current_ll_count": "BIGINT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_SAME_LEVEL_STATS_TABLE: {
        "stats_nk": "TEXT",
        "universe": "TEXT",
        "timeframe": "TEXT",
        "major_state": "TEXT",
        "metric_name": "TEXT",
        "sample_version": "TEXT",
        "sample_size": "BIGINT",
        "p10": "DOUBLE",
        "p25": "DOUBLE",
        "p50": "DOUBLE",
        "p75": "DOUBLE",
        "p90": "DOUBLE",
        "mean": "DOUBLE",
        "std": "DOUBLE",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_WAVE_LIFE_RUN_TABLE: {
        "run_id": "TEXT",
        "runner_name": "TEXT",
        "runner_version": "TEXT",
        "run_status": "TEXT",
        "execution_mode": "TEXT",
        "signal_start_date": "DATE",
        "signal_end_date": "DATE",
        "bounded_scope_count": "BIGINT",
        "claimed_scope_count": "BIGINT",
        "source_wave_table": "TEXT",
        "source_state_table": "TEXT",
        "source_stats_table": "TEXT",
        "sample_version": "TEXT",
        "life_contract_version": "TEXT",
        "started_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "summary_json": "TEXT",
    },
    MALF_WAVE_LIFE_WORK_QUEUE_TABLE: {
        "queue_nk": "TEXT",
        "scope_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "dirty_reason": "TEXT",
        "replay_start_bar_dt": "DATE",
        "replay_confirm_until_dt": "DATE",
        "source_fingerprint": "TEXT",
        "sample_version": "TEXT",
        "queue_status": "TEXT",
        "enqueued_at": "TIMESTAMP",
        "claimed_at": "TIMESTAMP",
        "completed_at": "TIMESTAMP",
        "first_seen_run_id": "TEXT",
        "last_claimed_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "updated_at": "TIMESTAMP",
    },
    MALF_WAVE_LIFE_CHECKPOINT_TABLE: {
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "last_completed_bar_dt": "DATE",
        "tail_start_bar_dt": "DATE",
        "tail_confirm_until_dt": "DATE",
        "last_sample_version": "TEXT",
        "source_fingerprint": "TEXT",
        "last_run_id": "TEXT",
        "updated_at": "TIMESTAMP",
    },
    MALF_WAVE_LIFE_SNAPSHOT_TABLE: {
        "snapshot_nk": "TEXT",
        "asset_type": "TEXT",
        "code": "TEXT",
        "timeframe": "TEXT",
        "asof_bar_dt": "DATE",
        "wave_id": "BIGINT",
        "source_wave_nk": "TEXT",
        "source_state_snapshot_nk": "TEXT",
        "major_state": "TEXT",
        "reversal_stage": "TEXT",
        "active_wave_bar_age": "BIGINT",
        "wave_life_percentile": "DOUBLE",
        "remaining_life_bars_p50": "DOUBLE",
        "remaining_life_bars_p75": "DOUBLE",
        "termination_risk_bucket": "TEXT",
        "sample_size": "BIGINT",
        "sample_version": "TEXT",
        "source_profile_nk": "TEXT",
        "profile_origin": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
    MALF_WAVE_LIFE_PROFILE_TABLE: {
        "profile_nk": "TEXT",
        "timeframe": "TEXT",
        "major_state": "TEXT",
        "reversal_stage": "TEXT",
        "metric_name": "TEXT",
        "sample_version": "TEXT",
        "sample_size": "BIGINT",
        "profile_origin": "TEXT",
        "p10": "DOUBLE",
        "p25": "DOUBLE",
        "p50": "DOUBLE",
        "p75": "DOUBLE",
        "p90": "DOUBLE",
        "mean": "DOUBLE",
        "std": "DOUBLE",
        "source_stats_nk": "TEXT",
        "first_seen_run_id": "TEXT",
        "last_materialized_run_id": "TEXT",
        "created_at": "TIMESTAMP",
        "updated_at": "TIMESTAMP",
    },
}
